# Generated by Django 4.1.3 on 2022-12-05 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='account',
            name='manager',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{10,12}$')]),
        ),
    ]
