# Generated by Django 4.0.6 on 2022-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0002_userorder_delivered_userorder_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'extra food',
                'verbose_name_plural': 'extra food',
            },
        ),
        migrations.AddField(
            model_name='userorder',
            name='extra_food',
            field=models.CharField(blank=True, max_length=255, verbose_name='Extra Food'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='user_comment',
            field=models.TextField(blank=True, max_length=255, verbose_name='User Comment'),
        ),
    ]
