# Generated by Django 4.1.3 on 2022-12-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0002_userorder_delivered_userorder_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='user_comment',
            field=models.TextField(blank=True, max_length=255, verbose_name='User Comment'),
        ),
    ]
