# Generated by Django 4.0.6 on 2022-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0003_extrafood_userorder_extra_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='extra_food',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra Food'),
        ),
    ]
