# Generated by Django 4.1.3 on 2022-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0003_userorder_user_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'extra food',
                'verbose_name_plural': 'extra food',
            },
        ),
    ]
