# Generated by Django 4.1.3 on 2022-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0004_extrafood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='extra_food',
            field=models.TextField(blank=True, max_length=255, verbose_name='Extra Food'),
        ),
    ]
