# Generated by Django 4.1.3 on 2022-12-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0008_foodmenu_with_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='quantity',
            field=models.CharField(max_length=255, verbose_name='Quantity'),
        ),
    ]
