# Generated by Django 4.1.3 on 2022-12-06 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madish_system', '0009_alter_userorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
